baseURL = 'https://meithal.github.io/godot-esgi-master4/'
languageCode = 'fr-FR'
title = 'Documentation projet Godot'
theme = 'hugo_theme_adam_eve'

[markup]
  [markup.tableOfContents]
    endLevel = 6
    ordered = false
    startLevel = 1
